#settings specifically for this models directory
#config other dbt settings within ~/.dbt/profiles.yml
source-paths: ["models"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["test"]

model-defaults:
  materialized: false
  enabled: false

models:
  zuora:
    enabled: true
    materialized: false
