#settings specifically for this models directory
#config other dbt settings within ~/.dbt/profiles.yml
name: 'ac_zendesk'
version: '1.0'

source-paths: ["models"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["test"]

model-defaults:
  materialized: false
  enabled: false

models:
  zendesk:
    enabled: true
    materialized: false
