--this file should contain all joins possible within the dataset.
--it's not yet clear exactly how these should be indicated.
--i had considered simply doing it via a bunch of select statements but
--there is probably a more elegant solution. worth thinking about more.
